Description: view docker build CFT
Parameters:
  CodeRepoName:
    Type: String
    Default: "view-app"
    Description: codecommit repo.
  CodeRepoBranchName:
    Type: String
    Default: "prod"
    Description: Code commit branch name
  ArtifactsBucket:
    Type: String
    Default: sagemaker-ap-southeast-1-588089106296
    Description: S3 bucket for storing code pipeline code.
  UsecaseName:
    Description: "Use Case Name"
    Type: String
    Default: "view-app-docker"
  AccountId:
    Description: "Account ID "
    Type: String
    Default: "588089106296"
Resources:

  ModelBuildCodeCommitEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Sub '${UsecaseName}-codecommit-pipeline-trigger'
      Description: >-
        Rule to trigger a deployment when CodeCommit repository is
        updated
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join
            - ':'
            - - arn
              - !Ref 'AWS::Partition'
              - codecommit
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - !Ref CodeRepoName
        detail:
          referenceType:
            - branch
          referenceName:
            - !Ref CodeRepoBranchName
      State: ENABLED
      Targets:
        - Arn: !Join
            - ':'
            - - arn
              - !Ref 'AWS::Partition'
              - codepipeline
              - !Ref 'AWS::Region'
              - !Ref AccountId
              - !Ref DockerBuildPipeline
          RoleArn: !Join
            - ':'
            - - arn
              - !Ref 'AWS::Partition'
              - 'iam:'
              - !Ref AccountId
              - role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          Id: !Sub 'codecommit-${UsecaseName}-modelbuild'

  DockerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      # Max length: 255 chars
      Name: !Sub ${UsecaseName}-Build # max: 10+33+15+10=68
      Description: Build docker image.
      ServiceRole: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref AccountId, 'role/service-role/AmazonSageMakerServiceCatalogProductsUseRole'] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 480

  DockerBuildPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      # Max length: 100 chars
      Name: !Sub ${UsecaseName}-buildpipeline # max: 10+33+15+10=68
      RoleArn:  !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref AccountId, 'role/service-role/AmazonSageMakerServiceCatalogProductsUseRole'] ]
      ArtifactStore:
        Type: S3
        Location:
          !Ref ArtifactsBucket

      Stages:
        - Name: Source
          Actions:
            - Name: ModelBuildWorkflowCode
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                # need to explicitly set this to false per https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html
                PollForSourceChanges: false
                RepositoryName: !Ref CodeRepoName
                BranchName: !Ref CodeRepoBranchName
              OutputArtifacts:
                - Name: ModelBuildSourceArtifact
        - Name: DockerBuild
          Actions:
            - Name: DockerBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: ModelBuildSourceArtifact
              OutputArtifacts:
                - Name: PreprocessingDockerArtifact

              Configuration:
                ProjectName: !Ref DockerBuildProject
              RunOrder: 1
